### ISSUE TITLE
Use custom DSL instead of filenames

### ISSUE THREAD

**Issue by keynmol** [idio/spotlight-model-editor#18]
Instead of basing everything on filenames, we could use a simple command-like language:

`MAKE <SurfaceForm> SPOTTABLE`

`MAKE <SurfaceForm> UNSPOTTABLE`

etc.

This will simplify adding more high-level commands like `MAKE <SurfaceForm> SOLE CANDIDATE FOR <TopicName>`.

**Comment by mal** [comment]
Closing as part of archiving process.
