### ISSUE TITLE
Make SF not spottable not working

### ISSUE THREAD

**Issue by tgalery** [idio/spotlight-model-editor#20]
Use case: the sf 'II' is associated to `World_War_II`. Making the sf not spottable doesn't remove it from the output topics

**Comment by Lugrin** [comment]
It's a feature. :D
It only makes the SF annotation probability lower, not null.

**Comment by tgalery** [comment]
Ok, in this case I will add the other topics to the current wolf pr then

**Comment by mal** [comment]
Closing as part of archiving process.
