### ISSUE TITLE
Silent Exceptions are masking something funny.

### ISSUE THREAD

**Issue by tgalery** [idio/spotlight-model-editor#21]
Use case: we add an association in new topics, .e.g. a line like this:

```
United_Kingdom_withdrawal_from_the_European_Union	brexit
```

which would associate the topic to the sf
For some reason, after the run the topic cannot be extracted from the sf, checking `rest/stats?sf=brexit` outputs something like this

```
{

    "sf": {
        "sf": "brexit",
        "annotatedCount": 1,
        "totalCount": 1,
        "annotationProbability": 1.0
    },
    "candidates": [
        {
            "percentage_of_context_vector": 0.39083206907945633,
            "support": 0,
            "prior": 0.0,
            "topic": {
                "uri": "United_Kingdom_withdrawal_from_the_European_Union",
                "prior": 6.183887386702955E-7,
                "support": 93
            },
            "surfaceForm": {
                "sf": "brexit",
                "annotatedCount": 1,
                "totalCount": 1,
                "annotationProbability": 1.0
            }
        }
    ]

}
```

Note that support and prior of the candidate is set to `0` and it seems that the topic doesn't even surface at the spotting phase. The output of `candidates` doesn't include the topic nor the sf even when all params are set to 0 in the request.

**Comment by tgalery** [comment]
The file was fed into flashlight and it didn't have any problems parsing the file

**Comment by mal** [comment]
Closing as part of archiving process.
